### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by lucasrcezimbra** [lucasrcezimbra/pyitau#16]
Add docstring and sphinx

- [x] Add Sphinx
- [x] Add initial structure
- [x] Add docstrings
- [x] Create readthedocs
- [x] Automatic deploy the docs

**Comment by DuyguKeskek** [comment]
Hi @Lrcezimbra, I want to take this issue and create a basic documentation layout that you can use, thanks!

**Comment by DuyguKeskek** [comment]
The issue is fixed here, please check : #21 
Thank you

**Comment by lucasrcezimbra** [comment]
Done in #194
