### ISSUE TITLE
Cartão de Crédito

### ISSUE THREAD

**Issue by OsnielLopes** [lucasrcezimbra/pyitau#58]
Atualmente são retornadas apenas as operações da conta corrente, certo? Qual a chance de conseguir também as transações do cartão de crédito?

**Comment by Lrcezimbra** [comment]
Sim, atualmente retorna somente dados da conta corrente. É bem provável conseguir buscar as transações de cartão de crédito. 

Já temos a parte da autenticação desenvolvida. Então poderia partir disso, acessar a página do cartão de crédito e recuperar os dados. O [get_statements](https://github.com/Lrcezimbra/pyitau/blob/master/pyitau/main.py#L41) faz isso pra buscar o extrato, seria o mesmo processo só que pro cartão de crédito.

Atualmente estou sem tempo para dedicar à isso. E não tenho cartão de crédito do Itaú para testar. Mas contribuições são bem-vindas, fique a vontade.

**Comment by lucasrcezimbra** [comment]
Closed by #171
