### ISSUE TITLE
Add comentários ao código

### ISSUE THREAD

**Issue by vmeazevedo** [lucasrcezimbra/pyitau#86]
Muito interessante o seu projeto, mas senti falta de comentários para auxiliar no entendimento da sua lógica. Naturalmente como você desenvolveu fica mais prático o seu entendimento, mas os outros usuários podem ter dificuldade de entendimento ou de até add novas funcionalidades. Caso seja possível, add comentários ao código para auxiliar manutenções futuras.

**Comment by lucasrcezimbra** [comment]
Olá, @vmeazevedo. 

Obrigado!

Chegou a ver os testes? Pode ajudar a clarear o entendimento. Lá tem uns mocks das respostas do Itaú.

Concordo que o código está complexo. Nos próximos dias vou fazer um refactor para simplificar o entendimento e a manutenção. Nas partes mais complexar vou adicionar comentários como sugerido.
